# Generated by Django 4.0 on 2021-12-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('esgScore', models.CharField(max_length=500)),
            ],
        ),
    ]
