# Generated by Django 4.0 on 2021-12-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('esgScore', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyData',
        ),
    ]
