# Generated by Django 4.0 on 2021-12-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sustainabilitycompanydata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='averageControversy',
        ),
    ]
