# Generated by Django 4.0 on 2021-12-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_sustainabilitycompanydata_palmoil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='alchoholic',
        ),
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='animalTesting',
        ),
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='catholic',
        ),
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='controversialWeapons',
        ),
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='environmentPercentile',
        ),
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='furLeather',
        ),
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='gambling',
        ),
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='gmo',
        ),
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='nuclear',
        ),
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='socialPercentile',
        ),
        migrations.RemoveField(
            model_name='sustainabilitycompanydata',
            name='tobacco',
        ),
    ]
