# Generated by Django 4.0 on 2021-12-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stocksustainabilitydata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
                ('priceDiff', models.CharField(max_length=500)),
            ],
        ),
    ]
