# Generated by Django 4.0 on 2021-12-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_pricedata_delete_stockpricedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500)),
                ('totalEsg', models.CharField(max_length=500)),
            ],
        ),
    ]
